language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"

env:
  - DJANGO=1.4.3
  - DJANGO=1.5.1

install:
  - pip install -q Django==$DJANGO --use-mirrors

script: python setup.py test

notifications:
  email:
    recipients:
      - bjasper@gmail.com
